name: "Run Container Scan on Super Mario Docker Image with Quality Gate"

on:
  push:
    branches:
      - master

env:
  VERSION: $(( $(cat version.txt) + 1 ))
  TRIVY_CACHE_DIR: ${{ github.workspace }}/.cache/trivy

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and Save Image
        run: |
          docker pull docker.io/sandeshsanthu/supermariogitopsproject:${{ env.VERSION }}
          mkdir -p $TRIVY_CACHE_DIR
          docker save -o supermariolatestdockerimage.tar docker.io/sandeshsanthu/supermariogitopsproject:${{ env.VERSION }}
          ls -la supermariolatestdockerimage.tar

      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          cache-dir: $TRIVY_CACHE_DIR
          input: ./supermariolatestdockerimage.tar
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
          format: 'json,sarif'
          output: './trivy-results'

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: ./trivy-results
